/// Divvy2SpikeRunner.swift
///
/// M0.5 architecture spike (THROWAWAY). Runs the 7 gated checks from
/// docs/2026-06-23-Design-M0.5-Architecture-Spike.md, writes SPIKE.md, logs
/// PASS/FAIL, and exits non-zero on any failure. Triggered only by the
/// `--divvy2-spike` launch argument, from the end of AppDelegate.accessibilityTrusted().

import Cocoa
import MASShortcut

enum Divvy2SpikeRunner {

    // MARK: - Result accumulation

    private final class Report {
        var lines: [String] = []
        var checkResults: [(name: String, passed: Bool, notReady: Bool)] = []

        func section(_ title: String) { lines.append("\n## \(title)\n") }
        func note(_ s: String) { lines.append(s) }
        func assert(_ cond: Bool, _ desc: String) -> Bool {
            lines.append("- [\(cond ? "PASS" : "FAIL")] \(desc)")
            return cond
        }
    }

    /// Idempotent cleanup, funneled from defer / atexit / DispatchSourceSignal.
    private static var cleanupBlocks: [() -> Void] = []
    private static var cleanupRan = false
    private static let cleanupQueue = DispatchQueue(label: "divvy2.spike.cleanup")
    private static func addCleanup(_ block: @escaping () -> Void) { cleanupBlocks.append(block) }
    private static func runCleanup() {
        cleanupQueue.sync {
            guard !cleanupRan else { return }
            cleanupRan = true
            for block in cleanupBlocks.reversed() { block() }
        }
    }

    // Retained for process lifetime so the dispatch handler actually runs (§3.1).
    private static var signalSources: [DispatchSourceSignal] = []

    // MARK: - Entry

    static func run(applicationToggle: ApplicationToggle?,
                    windowHistory: WindowHistory,
                    rectangleShortcutManager: ShortcutManager? = nil) {
        let report = Report()
        report.note("# SPIKE.md — Divvy-2 M0.5 architecture spike results")
        report.note("Generated by Divvy2SpikeRunner (--divvy2-spike). Throwaway de-risking harness.")

        // Crash-safe cleanup wiring (idempotent; safe to call from signal handler on main queue).
        for sig in [SIGINT, SIGTERM] {
            signal(sig, SIG_IGN)
            let src = DispatchSource.makeSignalSource(signal: sig, queue: .main)
            src.setEventHandler { runCleanup(); exit(2) }
            src.resume()
            signalSources.append(src)
        }
        atexit_b { runCleanup() }   // block variant; plain atexit can't capture context
        defer { runCleanup() }

        guard let applicationToggle else {
            report.note("\nENVIRONMENT-NOT-READY: applicationToggle is nil (Accessibility not granted).")
            finish(report, output: report.lines)
            return
        }

        // The isolated suite the conflict checks consult (never real prefs).
        let suiteName = "com.perg593.chiva.spike"
        let suite = UserDefaults(suiteName: suiteName)!
        suite.removePersistentDomain(forName: suiteName)
        addCleanup { suite.removePersistentDomain(forName: suiteName) }

        check1RegisterReloadOwnership(report, suite: suite)
        check2ConflictRejection(report, suite: suite)
        check3Lifecycle(report, applicationToggle: applicationToggle)
        check4And5WindowMoveAndCoordinates(report, windowHistory: windowHistory)
        check6Serialization(report)
        check7APIConfirmation(report)
        check8ProductionApplyNoHistory(report, windowHistory: windowHistory)
        check9SharedMonitorCoexistence(report, rectangleShortcutManager: rectangleShortcutManager)

        finish(report, output: report.lines)
    }

    private static func finish(_ report: Report, output: [String]) {
        let total = report.checkResults.count
        let passed = report.checkResults.filter { $0.passed }.count
        let allPass = report.checkResults.allSatisfy { $0.passed }
        let summary = "\nSPIKE RESULT: \(allPass ? "PASS" : "FAIL") (\(passed)/\(total))"
        report.note(summary)

        // Robust output path: env override, else the (always-writable) home dir.
        // Do NOT use currentDirectoryPath — an app launched via `open` has cwd "/".
        let outPath = ProcessInfo.processInfo.environment["DIVVY2_SPIKE_OUT"]
            ?? (NSHomeDirectory() as NSString).appendingPathComponent("divvy2-SPIKE.md")
        // Use report.lines (now incl. the summary just noted), not the pre-summary snapshot.
        _ = output
        let text = report.lines.joined(separator: "\n") + "\n"
        var writeError = "ok"
        do { try text.write(toFile: outPath, atomically: true, encoding: .utf8) }
        catch { writeError = "\(error)" }

        // Reliable side channel: NSLog goes to the unified log even when launched
        // via `open` (where stderr is swallowed). Emit a per-check summary too.
        NSLog("[divvy2-spike] %@", summary.trimmingCharacters(in: .whitespacesAndNewlines))
        for r in report.checkResults {
            NSLog("[divvy2-spike] %@: %@", r.name, r.notReady ? "NOT-READY" : (r.passed ? "PASS" : "FAIL"))
        }
        NSLog("[divvy2-spike] wrote %@ (write: %@)", outPath, writeError)
        FileHandle.standardError.write(Data((text + "\n[divvy2-spike] wrote \(outPath)\n").utf8))
        runCleanup()
        exit(allPass ? 0 : 1)
    }

    private static func record(_ report: Report, name: String, passed: Bool, notReady: Bool = false) {
        report.checkResults.append((name, passed, notReady))
        report.note("\n**\(name): \(notReady ? "ENVIRONMENT-NOT-READY/FAIL" : (passed ? "PASS" : "FAIL"))**")
    }

    // MARK: - Helpers

    private static func mas(_ keyCode: Int, _ flags: NSEvent.ModifierFlags) -> MASShortcut {
        MASShortcut(keyCode: keyCode, modifierFlags: flags)
    }

    /// Write a MASShortcut into a defaults suite under a WindowAction key, exactly
    /// as Rectangle persists it (MASDictionaryTransformer).
    private static func inject(_ shortcut: MASShortcut, forAction action: WindowAction, into defaults: UserDefaults) {
        guard let t = ValueTransformer(forName: NSValueTransformerName(rawValue: MASDictionaryTransformerName)),
              let dict = t.reverseTransformedValue(shortcut) else { return }
        defaults.set(dict, forKey: action.name)
    }

    private static func waitUntil(timeout: TimeInterval, poll: TimeInterval = 0.05, _ cond: () -> Bool) -> Bool {
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            if cond() { return true }
            RunLoop.current.run(until: Date().addingTimeInterval(poll))
        }
        return cond()
    }

    // MARK: - Check 1: register + reload + non-mutating ownership

    private static func check1RegisterReloadOwnership(_ report: Report, suite: UserDefaults) {
        report.section("Check 1 — register + reload + ownership (non-mutating)")
        // Empty conflict defaults so our novel chords never collide with real prefs.
        let conflicts = UserDefaults(suiteName: "com.perg593.chiva.spike.c1")!
        conflicts.removePersistentDomain(forName: "com.perg593.chiva.spike.c1")
        let mgr = SpikeCustomLayoutShortcutManager(conflictDefaults: conflicts)
        addCleanup { mgr.unregisterAllOwned() }

        var hits = [UUID: Int]()
        let idA = UUID(), idB = UUID()
        let cA = mas(96, [.command, .control, .option])   // F5-ish
        let cB = mas(97, [.command, .control, .option])   // F6-ish
        let rA = mgr.bind(layoutId: idA, shortcut: cA) { hits[idA, default: 0] += 1 }
        let rB = mgr.bind(layoutId: idB, shortcut: cB) { hits[idB, default: 0] += 1 }

        var ok = true
        ok = report.assert(rA == .registered && rB == .registered, "both novel chords registered (monitor returned true)") && ok
        ok = report.assert(mgr.owned.count == 2 && mgr.registerCalls == 2, "manager tracks exactly 2 owned chords, 2 register calls") && ok
        mgr.fireForTest(layoutId: idA); mgr.fireForTest(layoutId: idB)
        ok = report.assert(hits[idA] == 1 && hits[idB] == 1, "each stored closure fires exactly once when invoked") && ok

        // Unregister one, re-register from a simulated store change.
        mgr.unbind(layoutId: idB)
        ok = report.assert(mgr.owned[idB] == nil && mgr.unregisterCalls == 1, "unbind removes only the owned chord (1 unregister call)") && ok
        let rB2 = mgr.bind(layoutId: idB, shortcut: cB) { hits[idB, default: 0] += 1 }
        ok = report.assert(rB2 == .registered && mgr.owned.count == 2, "re-register after store-change succeeds, no leak") && ok

        // Non-mutating ownership guard: a stand-in 'existing binding' must survive a rejected duplicate.
        let standIn = mas(98, [.command, .control, .option]) // F7-ish
        var standInHits = 0
        let standInRegistered = MASShortcutMonitor.shared().register(standIn) { standInHits += 1 }
        addCleanup { MASShortcutMonitor.shared().unregisterShortcut(standIn) }
        inject(standIn, forAction: .leftHalf, into: conflicts) // model it as a live WindowAction binding
        let beforeReg = mgr.registerCalls, beforeUnreg = mgr.unregisterCalls
        let rDup = mgr.bind(layoutId: UUID(), shortcut: standIn) { }
        ok = report.assert(standInRegistered, "stand-in 'existing' binding registered on shared monitor") && ok
        ok = report.assert(rDup == .rejectedConflictWindowAction(WindowAction.leftHalf.name),
                           "manager rejects a duplicate of an existing WindowAction chord") && ok
        ok = report.assert(mgr.registerCalls == beforeReg && mgr.unregisterCalls == beforeUnreg,
                           "ZERO monitor register/unregister calls for the rejected chord (ownership preserved)") && ok
        standInHits = 0
        // The stand-in closure is intact (we never tore it down).
        ok = report.assert({ () -> Bool in
            // invoke our retained stand-in action proxy by re-registering identity check is unsafe;
            // instead prove non-teardown by confirming a second register of the same chord FAILS
            // (still registered) — MASShortcutMonitor rejects duplicate registration.
            let stillRegistered = !MASShortcutMonitor.shared().register(standIn) { }
            return stillRegistered
        }(), "stand-in chord remains registered after the rejected duplicate") && ok

        record(report, name: "Check 1", passed: ok)
    }

    // MARK: - Check 2: conflict rejection

    private static func check2ConflictRejection(_ report: Report, suite: UserDefaults) {
        report.section("Check 2 — conflict rejection (isolated suite)")
        let conflicts = UserDefaults(suiteName: "com.perg593.chiva.spike.c2")!
        conflicts.removePersistentDomain(forName: "com.perg593.chiva.spike.c2")
        addCleanup { conflicts.removePersistentDomain(forName: "com.perg593.chiva.spike.c2") }

        // Inject a live WindowAction shortcut (leftHalf = ctrl+opt+Left) into the isolated suite.
        let waChord = mas(123, [.control, .option]) // 123 = left arrow
        inject(waChord, forAction: .leftHalf, into: conflicts)
        let mgr = SpikeCustomLayoutShortcutManager(conflictDefaults: conflicts)
        addCleanup { mgr.unregisterAllOwned() }

        var ok = true
        let rWA = mgr.bind(layoutId: UUID(), shortcut: mas(123, [.control, .option])) { }
        ok = report.assert(rWA == .rejectedConflictWindowAction(WindowAction.leftHalf.name) && mgr.registerCalls == 0,
                           "duplicate of a live WindowAction chord rejected, no monitor call") && ok

        let free1 = mas(99, [.command, .control, .option])
        let rFree = mgr.bind(layoutId: UUID(), shortcut: free1) { }
        ok = report.assert(rFree == .registered, "non-conflicting chord registered (true)") && ok

        let rCustomDup = mgr.bind(layoutId: UUID(), shortcut: mas(99, [.command, .control, .option])) { }
        let regCallsAfter = mgr.registerCalls
        ok = report.assert(rCustomDup == .rejectedConflictCustom, "duplicate of an owned custom chord rejected") && ok
        ok = report.assert(regCallsAfter == 1, "exactly one monitor register call across check 2 (only the free chord)") && ok

        record(report, name: "Check 2", passed: ok)
    }

    // MARK: - Check 3: lifecycle suppression

    private static func check3Lifecycle(_ report: Report, applicationToggle: ApplicationToggle) {
        report.section("Check 3 — lifecycle suppression (recording + shortcutsDisabled)")
        let conflicts = UserDefaults(suiteName: "com.perg593.chiva.spike.c3")!
        conflicts.removePersistentDomain(forName: "com.perg593.chiva.spike.c3")
        addCleanup { conflicts.removePersistentDomain(forName: "com.perg593.chiva.spike.c3") }
        let mgr = SpikeCustomLayoutShortcutManager(conflictDefaults: conflicts)
        mgr.startObservingRecording()
        addCleanup { mgr.unregisterAllOwned() }

        var fires = 0
        let id = UUID()
        _ = mgr.bind(layoutId: id, shortcut: mas(100, [.command, .control, .option])) { fires += 1 } // 100 = F8

        var ok = true
        // Recording suppression.
        Notification.Name.shortcutRecording.post(object: true)
        _ = waitUntil(timeout: 0.5) { mgr.suspendedForRecording }
        let suppressedWhileRecording = (mgr.fireForTest(layoutId: id) == false)
        ok = report.assert(suppressedWhileRecording, "custom chord suppressed while a shortcut is being recorded") && ok
        Notification.Name.shortcutRecording.post(object: false)
        _ = waitUntil(timeout: 0.5) { !mgr.suspendedForRecording }
        let firesAfter = (mgr.fireForTest(layoutId: id) == true)
        ok = report.assert(firesAfter, "custom chord resumes after recording ends") && ok

        // Disabled-state — only valid from an initially ENABLED state.
        if ApplicationToggle.shortcutsDisabled {
            ok = report.assert(false, "ENVIRONMENT-NOT-READY: shortcuts already disabled at entry") && ok
            record(report, name: "Check 3", passed: false, notReady: true)
            return
        }
        let initial = ApplicationToggle.shortcutsDisabled // false
        let disabledSnapshot = Defaults.disabledApps.value
        let fakeId = "com.perg593.chiva.spike.fakeapp"
        // Idempotent teardown wired into cleanup as well.
        let restore: () -> Void = {
            applicationToggle.enableApp(appBundleId: fakeId)
            Defaults.disabledApps.value = disabledSnapshot
            applicationToggle.reloadFromDefaults()
        }
        addCleanup(restore)

        applicationToggle.disableApp(appBundleId: fakeId)
        let flagWentTrue = ApplicationToggle.shortcutsDisabled == true
        let suppressedWhileDisabled = (mgr.fireForTest(layoutId: id) == false)
        restore()
        let flagBack = ApplicationToggle.shortcutsDisabled == initial
        let firesWhenEnabled = (mgr.fireForTest(layoutId: id) == true)

        ok = report.assert(flagWentTrue, "disableApp flips the real ApplicationToggle.shortcutsDisabled to true") && ok
        ok = report.assert(suppressedWhileDisabled, "custom chord suppressed while shortcuts disabled") && ok
        ok = report.assert(flagBack, "flag returned to its initial value after restore (reloadFromDefaults)") && ok
        ok = report.assert(firesWhenEnabled, "custom chord resumes once shortcuts re-enabled") && ok
        report.note("- [NOTE] residual risk: a hard crash between disableApp and cleanup could leave the UNIQUE fake bundle id in Defaults.disabledApps (harmless — it matches no real app; restored on normal/atexit/signal exit).")

        record(report, name: "Check 3", passed: ok)
    }

    // MARK: - Checks 4 & 5: real cross-app window move + coordinate contract

    private static func check4And5WindowMoveAndCoordinates(_ report: Report, windowHistory: WindowHistory) {
        report.section("Checks 4 & 5 — cross-app window move + coordinate contract (helper app)")

        let helperURL = Bundle.main.bundleURL.deletingLastPathComponent()
            .appendingPathComponent("Divvy2SpikeHelper.app")
        guard FileManager.default.fileExists(atPath: helperURL.path) else {
            report.note("- [SKIP] Divvy2SpikeHelper.app not found at \(helperURL.path)")
            record(report, name: "Check 4", passed: false, notReady: true)
            record(report, name: "Check 5", passed: false, notReady: true)
            return
        }

        // Refuse to proceed if a helper instance is somehow already running.
        let already = NSRunningApplication.runningApplications(withBundleIdentifier: "com.perg593.chiva.spikehelper")
        if !already.isEmpty {
            report.note("- [SKIP] a Divvy2SpikeHelper instance is already running")
            record(report, name: "Check 4", passed: false, notReady: true)
            record(report, name: "Check 5", passed: false, notReady: true)
            return
        }

        // Launch a fresh helper instance and acquire its focused window.
        let config = NSWorkspace.OpenConfiguration()
        config.activates = true
        config.createsNewApplicationInstance = true
        var launched: NSRunningApplication?
        let sem = DispatchSemaphore(value: 0)
        NSWorkspace.shared.openApplication(at: helperURL, configuration: config) { app, _ in
            launched = app; sem.signal()
        }
        _ = sem.wait(timeout: .now() + 5)
        guard let helperApp = launched else {
            report.note("- [FAIL] could not launch Divvy2SpikeHelper")
            record(report, name: "Check 4", passed: false, notReady: true)
            record(report, name: "Check 5", passed: false, notReady: true)
            return
        }
        let helperPID = helperApp.processIdentifier
        addCleanup { helperApp.forceTerminate() }

        _ = waitUntil(timeout: 3) {
            NSWorkspace.shared.frontmostApplication?.processIdentifier == helperPID
        }
        // Target the helper window BY PID (deterministic; never the user's frontmost window).
        let appEl = AccessibilityElement(helperPID)
        let windowReady = waitUntil(timeout: 3) {
            guard let w = appEl.windowElements?.first else { return false }
            return !w.frame.isNull
        }
        guard windowReady,
              let windowEl = appEl.windowElements?.first,
              windowEl.isWindow == true, windowEl.pid == helperPID else {
            report.note("- [FAIL] helper window not acquirable by PID (ready=\(windowReady))")
            record(report, name: "Check 4", passed: false, notReady: true)
            record(report, name: "Check 5", passed: false, notReady: true)
            return
        }
        report.note("- [DIAG] helperPID=\(helperPID) windowEl.pid=\(windowEl.pid ?? -1) AXframeBefore=\(rectStr(windowEl.frame))")
        report.note("- [DIAG] CGWindows(helper) before: \(dumpCGWindows(pid: helperPID))")

        // Target screen + raw visibleFrame (gap = 0).
        guard let screens = ScreenDetection().detectScreens(using: windowEl) else {
            report.note("- [FAIL] ScreenDetection returned nil")
            record(report, name: "Check 4", passed: false, notReady: true)
            record(report, name: "Check 5", passed: false, notReady: true)
            return
        }
        let visible = screens.currentScreen.visibleFrame
        let primaryMaxY = NSScreen.screens[0].frame.maxY

        func moveAndReadBack(_ norm: SpikeNormalizedRect) -> CGRect? {
            let appKit = norm.appKitRect(in: visible)
            let expected = expectedAX(appKit, primaryMaxY)
            windowEl.setFrame(appKit.screenFlipped)
            _ = waitUntil(timeout: 1.0) { _approxEqual(windowEl.frame, expected, tol: 2) }
            // Let the window server catch up so CGWindowList reflects the move.
            _ = waitUntil(timeout: 1.0) { (cgWindowBounds(pid: helperPID).map { _approxEqual($0, expected, tol: 2) }) ?? false }
            return windowEl.frame
        }

        // --- Check 4: move + no history writes ---
        let beforeRestore = windowHistory.restoreRects
        // Compare full VALUES (not just keys) of lastRectangleActions via a stable projection.
        let beforeActions = String(describing: windowHistory.lastRectangleActions)
        let full = SpikeNormalizedRect(x: 0.05, y: 0.05, w: 0.9, h: 0.9)
        let readBack1 = moveAndReadBack(full)
        let readBack2 = moveAndReadBack(full) // idempotency
        var ok4 = true
        ok4 = report.assert(readBack1 != nil && _approxEqual(readBack1!, expectedAX(full.appKitRect(in: visible), primaryMaxY), tol: 2),
                            "window moved to target (AX read-back within 2px)") && ok4
        ok4 = report.assert(readBack1 != nil && readBack2 != nil && _approxEqual(readBack1!, readBack2!, tol: 2),
                            "repeated move is idempotent (no drift)") && ok4
        let historyUnchanged = (windowHistory.restoreRects == beforeRestore)
            && (String(describing: windowHistory.lastRectangleActions) == beforeActions)
        ok4 = report.assert(historyUnchanged, "no writes to windowHistory.restoreRects / lastRectangleActions (full value compare)") && ok4
        record(report, name: "Check 4", passed: ok4)

        // --- Check 5: coordinate contract with independent ground truth ---
        var ok5 = true
        let topHalf = SpikeNormalizedRect(x: 0, y: 0, w: 1, h: 0.5)
        let bottomHalf = SpikeNormalizedRect(x: 0, y: 0.5, w: 1, h: 0.5)
        let topAppKit = topHalf.appKitRect(in: visible)
        let bottomAppKit = bottomHalf.appKitRect(in: visible)

        let topRead = moveAndReadBack(topHalf)
        let topExpected = expectedAX(topAppKit, primaryMaxY) // computed WITHOUT screenFlipped
        ok5 = report.assert(topRead != nil && _approxEqual(topRead!, topExpected, tol: 2),
                            "top-half AX frame matches independent expected (primaryMaxY - maxY)") && ok5
        let topCG = cgWindowBounds(pid: helperPID)
        report.note("- [DIAG] top-half: AXread=\(rectStr(topRead)) expectedAX=\(rectStr(topExpected)) CGbounds=\(rectStr(topCG)) visibleFrame=\(rectStr(visible)) primaryMaxY=\(Int(primaryMaxY))")
        report.note("- [DIAG] CGWindows(helper) after top-move: \(dumpCGWindows(pid: helperPID))")
        ok5 = report.assert(topCG != nil && _approxEqual(topCG!, expectedTopLeft(topAppKit, primaryMaxY), tol: 2),
                            "top-half CGWindowList bounds (top-left global) match independent expected") && ok5

        let bottomRead = moveAndReadBack(bottomHalf)
        let bottomExpected = expectedAX(bottomAppKit, primaryMaxY)
        ok5 = report.assert(bottomRead != nil && _approxEqual(bottomRead!, bottomExpected, tol: 2),
                            "bottom-half AX frame matches independent expected") && ok5
        // Sign check: in AX (top-left origin) the top half has a SMALLER origin.y than the bottom half.
        if let t = topRead, let b = bottomRead {
            ok5 = report.assert(t.origin.y < b.origin.y, "top-half AX origin.y < bottom-half origin.y (Y-axis not flipped)") && ok5
        } else { ok5 = false }

        if screens.numScreens < 2 {
            report.note("- [INFO] only one display present: secondary-display sub-case recorded as unavailable hardware (gate still passes); validated primary visibleFrame instead.")
        }
        record(report, name: "Check 5", passed: ok5)
    }

    // independent expected AX rect (top-left, primary-referenced) from an AppKit rect.
    private static func expectedAX(_ appKit: CGRect, _ primaryMaxY: CGFloat) -> CGRect {
        CGRect(x: appKit.origin.x, y: primaryMaxY - appKit.maxY, width: appKit.width, height: appKit.height)
    }
    private static func expectedTopLeft(_ appKit: CGRect, _ primaryMaxY: CGFloat) -> CGRect {
        // CGWindowList bounds are top-left global, same as the expected AX rect here.
        expectedAX(appKit, primaryMaxY)
    }
    private static func _approxEqual(_ a: CGRect, _ b: CGRect, tol: CGFloat) -> Bool {
        abs(a.origin.x - b.origin.x) <= tol && abs(a.origin.y - b.origin.y) <= tol
            && abs(a.width - b.width) <= tol && abs(a.height - b.height) <= tol
    }
    private static func rectStr(_ r: CGRect?) -> String {
        guard let r = r, !r.isNull else { return "nil" }
        return "(\(Int(r.minX)),\(Int(r.minY)) \(Int(r.width))x\(Int(r.height)))"
    }
    private static func dumpCGWindows(pid: pid_t) -> String {
        guard let list = CGWindowListCopyWindowInfo([.optionAll], kCGNullWindowID) as? [[String: Any]] else { return "nil" }
        let mine = list.filter { ($0[kCGWindowOwnerPID as String] as? pid_t) == pid }
        if mine.isEmpty { return "(none)" }
        return mine.map { info in
            let layer = info[kCGWindowLayer as String] as? Int ?? -1
            let title = info[kCGWindowName as String] as? String ?? ""
            let b = (info[kCGWindowBounds as String] as? [String: Any]).flatMap { CGRect(dictionaryRepresentation: $0 as CFDictionary) }
            return "[layer=\(layer) bounds=\(rectStr(b)) title=\"\(title)\"]"
        }.joined(separator: " ")
    }
    private static func cgWindowBounds(pid: pid_t) -> CGRect? {
        guard let infoList = CGWindowListCopyWindowInfo([.optionOnScreenOnly, .excludeDesktopElements], kCGNullWindowID) as? [[String: Any]] else { return nil }
        for info in infoList {
            guard let ownerPID = info[kCGWindowOwnerPID as String] as? pid_t, ownerPID == pid,
                  let layer = info[kCGWindowLayer as String] as? Int, layer == 0,
                  let boundsDict = info[kCGWindowBounds as String] as? [String: Any],
                  let bounds = CGRect(dictionaryRepresentation: boundsDict as CFDictionary)
            else { continue }
            return bounds
        }
        return nil
    }

    // MARK: - Check 6: hotkey serialization

    private static func check6Serialization(_ report: Report) {
        report.section("Check 6 — hotkey serialization (MASDictionaryTransformer ⇄ SpikeHotkeyData)")
        var ok = true
        let shortcut = mas(124, [.command, .shift]) // 124 = right arrow
        guard let t = ValueTransformer(forName: NSValueTransformerName(rawValue: MASDictionaryTransformerName)) else {
            record(report, name: "Check 6", passed: false, notReady: true); return
        }
        let dict = t.reverseTransformedValue(shortcut) as? [String: Any]
        let keyCodeVal = dict?["keyCode"] as? Int
        let modVal = dict?["modifierFlags"] as? UInt
        let dictKeys = Set((dict ?? [:]).keys)
        ok = report.assert(dict != nil && dictKeys == ["keyCode", "modifierFlags"]
                           && keyCodeVal == shortcut.keyCode && modVal == shortcut.modifierFlags.rawValue,
                           "MASDictionaryTransformer emits EXACTLY {keyCode, modifierFlags} (\(dictKeys.sorted()))") && ok
        if let dict {
            let back = t.transformedValue(dict) as? MASShortcut
            ok = report.assert(back?.keyCode == shortcut.keyCode && back?.modifierFlags == shortcut.modifierFlags,
                               "transformedValue reproduces an equal MASShortcut") && ok
        }
        // Recorder-emission proof: a REAL MASShortcutView bound to a temp key emits the same dict.
        let recKey = "com.perg593.chiva.spike.recorder." + UUID().uuidString
        addCleanup { UserDefaults.standard.removeObject(forKey: recKey) } // crash-safe temp-key removal
        let view = MASShortcutView()
        view.setAssociatedUserDefaultsKey(recKey, withTransformerName: MASDictionaryTransformerName)
        view.shortcutValue = shortcut
        _ = waitUntil(timeout: 0.5) { UserDefaults.standard.dictionary(forKey: recKey) != nil }
        let emitted = UserDefaults.standard.dictionary(forKey: recKey)
        let emittedKeys = Set((emitted ?? [:]).keys)
        ok = report.assert(emitted != nil && emittedKeys == ["keyCode", "modifierFlags"]
                           && (emitted?["keyCode"] as? Int) == shortcut.keyCode
                           && (emitted?["modifierFlags"] as? UInt) == shortcut.modifierFlags.rawValue,
                           "MASShortcutView recorder emits the SAME {keyCode, modifierFlags} dict to defaults") && ok
        UserDefaults.standard.removeObject(forKey: recKey)
        // SpikeHotkeyData mirrors that dict and JSON round-trips.
        let hk = SpikeHotkeyData(shortcut)
        ok = report.assert(hk.keyCode == shortcut.keyCode && hk.modifierFlags == shortcut.modifierFlags.rawValue,
                           "SpikeHotkeyData captures keyCode + modifierFlags") && ok
        if let data = try? JSONEncoder().encode(hk), let decoded = try? JSONDecoder().decode(SpikeHotkeyData.self, from: data) {
            ok = report.assert(decoded == hk && decoded.toMASShortcut().keyCode == shortcut.keyCode
                               && decoded.toMASShortcut().modifierFlags == shortcut.modifierFlags,
                               "SpikeHotkeyData JSON round-trip preserves the chord (schemaVersion \(hk.schemaVersion))") && ok
        } else { ok = false }
        report.note("- Canonical SpikeHotkeyData: `{ keyCode: Int, modifierFlags: UInt, schemaVersion: Int = 1 }`, persisted under `com.perg593.chiva.customLayouts`. Proven above that the real MASShortcutView recorder emits exactly this `{keyCode, modifierFlags}` dict — so SpikeHotkeyData is interchangeable with the recorder's on-disk output.")
        record(report, name: "Check 6", passed: ok)
    }

    // MARK: - Check 7: API confirmation

    private static func check7APIConfirmation(_ report: Report) {
        report.section("Check 7 — confirmed Rectangle/MASShortcut APIs (no guessed names)")
        let confirmed = [
            "Apply path: AccessibilityElement.getFrontWindowElement() / setFrame(_:adjustSizeFirst:) / frame (AccessibilityElement.swift)",
            "Coordinate flip: CGRect.screenFlipped about NSScreen.screens[0].frame.maxY (Utilities/CGExtension.swift)",
            "Screen pick: ScreenDetection().detectScreens(using:) -> UsableScreens; screenContaining largest-intersection (ScreenDetection.swift)",
            "Hotkeys (parallel): MASShortcutMonitor.shared().registerShortcut(_:withAction:) -> Bool / unregisterShortcut(_:)",
            "Recorder UI: MASShortcutView (storyboard customClass), bound via setAssociatedUserDefaultsKey + MASDictionaryTransformerName",
            "Conflict: ShortcutCycle.ShortcutIdentity {keyCode, modifierFlags} + ShortcutCycle.shortcut(for:userDefaults:)",
            "Lifecycle: Notification.Name.shortcutRecording (Bool) + ApplicationToggle.shortcutsDisabled / disableApp/enableApp",
            "History (bypassed): WindowHistory.restoreRects / lastRectangleActions; written only by WindowManager.execute + SnappingManager",
            "Bypassed action system: enum WindowAction: Int + static active; WindowManager.execute(ExecutionParameters)",
            "Canonical serialization mirror: struct Shortcut: Codable {keyCode: Int, modifierFlags: UInt} (WindowAction.swift)",
        ]
        for c in confirmed { report.note("- \(c)") }
        record(report, name: "Check 7", passed: true)
    }

    // MARK: - Check 8: PRODUCTION manager apply + no history

    private static func check8ProductionApplyNoHistory(_ report: Report, windowHistory: WindowHistory) {
        report.section("Check 8 — production CustomLayoutShortcutManager apply + no history")
        let helperURL = Bundle.main.bundleURL.deletingLastPathComponent()
            .appendingPathComponent("Divvy2SpikeHelper.app")
        guard FileManager.default.fileExists(atPath: helperURL.path) else {
            report.note("- [SKIP] helper app not built")
            record(report, name: "Check 8", passed: false, notReady: true); return
        }
        // Our own disposable helper: a fresh instance is launched and targeted by its
        // PID, so it's fine if Check 4/5's instance is still alive (terminated at end).
        let config = NSWorkspace.OpenConfiguration()
        config.activates = true; config.createsNewApplicationInstance = true
        var launched: NSRunningApplication?
        let sem = DispatchSemaphore(value: 0)
        NSWorkspace.shared.openApplication(at: helperURL, configuration: config) { app, _ in launched = app; sem.signal() }
        _ = sem.wait(timeout: .now() + 5)
        guard let helperApp = launched else {
            report.note("- [FAIL] could not launch helper")
            record(report, name: "Check 8", passed: false, notReady: true); return
        }
        let pid = helperApp.processIdentifier
        addCleanup { helperApp.forceTerminate() }
        _ = waitUntil(timeout: 3) { NSWorkspace.shared.frontmostApplication?.processIdentifier == pid }
        let appEl = AccessibilityElement(pid)
        _ = waitUntil(timeout: 3) { appEl.windowElements?.first.map { !$0.frame.isNull } ?? false }
        guard let windowEl = appEl.windowElements?.first,
              let screens = ScreenDetection().detectScreens(using: windowEl) else {
            report.note("- [FAIL] helper window/screen not acquirable")
            record(report, name: "Check 8", passed: false, notReady: true); return
        }

        let suiteName = "com.perg593.chiva.spike.c8"
        let suite = UserDefaults(suiteName: suiteName)!
        suite.removePersistentDomain(forName: suiteName)
        addCleanup { suite.removePersistentDomain(forName: suiteName) }
        let store = CustomLayoutStore(userDefaults: suite)
        let id = UUID()
        store.add(CustomLayout(id: id, name: "left60", rect: NormalizedRect(x: 0, y: 0, w: 0.6, h: 1)))
        // No rectangle manager / no chord needed: triggerForTest exercises the apply path directly.
        let mgr = CustomLayoutShortcutManager(store: store,
                                              conflictDefaults: suite, monitor: MASShortcutMonitor.shared())
        addCleanup { mgr.stop() }

        let visible = screens.currentScreen.visibleFrame
        let expectedAppKit = NormalizedRect(x: 0, y: 0, w: 0.6, h: 1).pixelRect(in: visible)
        let expectedAXrect = expectedAX(expectedAppKit, NSScreen.screens[0].frame.maxY)

        let beforeRestore = windowHistory.restoreRects
        let beforeActions = String(describing: windowHistory.lastRectangleActions)
        mgr.triggerForTest(id)
        _ = waitUntil(timeout: 1.0) { _approxEqual(appEl.windowElements?.first?.frame ?? .null, expectedAXrect, tol: 2) }

        var ok = true
        let readBack = appEl.windowElements?.first?.frame
        ok = report.assert(readBack != nil && _approxEqual(readBack!, expectedAXrect, tol: 2),
                           "production manager moved helper to layout pixelRect \(rectStr(readBack))") && ok
        let historyUnchanged = windowHistory.restoreRects == beforeRestore
            && String(describing: windowHistory.lastRectangleActions) == beforeActions
        ok = report.assert(historyUnchanged, "production apply wrote nothing to windowHistory") && ok
        record(report, name: "Check 8", passed: ok)
    }

    // MARK: - Check 9: shared-monitor coexistence (custom yields to WindowAction)

    private static func check9SharedMonitorCoexistence(_ report: Report, rectangleShortcutManager: ShortcutManager?) {
        report.section("Check 9 — shared-monitor coexistence (REAL Rectangle reclaim)")
        guard let rectMgr = rectangleShortcutManager else {
            report.note("- [SKIP] no rectangleShortcutManager available")
            record(report, name: "Check 9", passed: false, notReady: true); return
        }
        // Use the REAL standard defaults Rectangle reads, so its binder actually sees the
        // conflict and reclaims the chord. Snapshot/restore the touched WindowAction key.
        let std = UserDefaults.standard
        let leftHalfKey = WindowAction.leftHalf.name
        // Snapshot the PERSISTENT (on-disk) override, NOT the effective value — otherwise a
        // key that was merely inherited from registered defaults would get written back as a
        // persistent user value on restore, mutating real prefs.
        let domain = Bundle.main.bundleIdentifier ?? "com.perg593.chiva"
        let savedLeftHalf = std.persistentDomain(forName: domain)?[leftHalfKey]
        addCleanup {
            if let saved = savedLeftHalf { std.set(saved, forKey: leftHalfKey) }
            else { std.removeObject(forKey: leftHalfKey) }   // revert to inherited default
            rectMgr.reloadFromDefaults()   // restore Rectangle to its original bindings
        }

        let suiteName = "com.perg593.chiva.spike.c9"
        let suite = UserDefaults(suiteName: suiteName)!
        suite.removePersistentDomain(forName: suiteName)
        addCleanup { suite.removePersistentDomain(forName: suiteName) }

        let store = CustomLayoutStore(userDefaults: suite)
        let idX = UUID(), idY = UUID()
        let chordX = mas(101, [.command, .control, .option])   // novel (unlikely a real shortcut)
        let chordY = mas(103, [.command, .control, .option])
        store.add(CustomLayout(id: idX, name: "X", rect: NormalizedRect(x: 0, y: 0, w: 0.5, h: 1), hotkey: HotkeyData(chordX)))
        store.add(CustomLayout(id: idY, name: "Y", rect: NormalizedRect(x: 0.5, y: 0, w: 0.5, h: 1), hotkey: HotkeyData(chordY)))
        // conflictDefaults = the REAL standard defaults, and reclaim drives the REAL Rectangle manager.
        let mgr = CustomLayoutShortcutManager(store: store,
                                              reclaim: { rectMgr.reloadFromDefaults() },
                                              conflictDefaults: std, monitor: MASShortcutMonitor.shared())
        addCleanup { mgr.stop() }

        var ok = true
        mgr.reconcileNow()
        ok = report.assert(mgr.outcomes[idX] == .registered && mgr.outcomes[idY] == .registered,
                           "both novel custom chords registered on the real shared monitor") && ok

        // A real WindowAction (leftHalf) now takes chord X in standard defaults.
        inject(chordX, forAction: .leftHalf, into: std)
        mgr.reconcileNow()   // yields X (conflictWindowAction) + reclaim → Rectangle binds chordX→leftHalf
        ok = report.assert(mgr.outcomes[idX] == .conflictWindowAction(WindowAction.leftHalf.name),
                           "custom yields chord X to the WindowAction") && ok
        ok = report.assert(mgr.outcomes[idY] == .registered, "non-conflicting custom chord Y stays owned") && ok
        // Real coexistence proof: chord X is now owned by RECTANGLE, so a fresh register must FAIL.
        let secondRegister = MASShortcutMonitor.shared().register(chordX) { }
        if secondRegister { MASShortcutMonitor.shared().unregisterShortcut(chordX) } // unexpected: clean up
        ok = report.assert(!secondRegister,
                           "after yield + reclaim, Rectangle owns chord X (a second register fails)") && ok
        record(report, name: "Check 9", passed: ok)
    }
}
